Application has thrown an uncaught exception and is terminated:
MongoError: auth fails
    at Object.exports.toError (\\10.207.188.48\volume-22-default\b6e1596fdce18f78aadb\eb3fb43bd98e49bd92d5e543ca052dcc\site\wwwroot\node_modules\mongodb\lib\mongodb\utils.js:108:11)
    at Db.authenticate (\\10.207.188.48\volume-22-default\b6e1596fdce18f78aadb\eb3fb43bd98e49bd92d5e543ca052dcc\site\wwwroot\node_modules\mongodb\lib\mongodb\db.js:670:31)
    at Db._executeQueryCommand (\\10.207.188.48\volume-22-default\b6e1596fdce18f78aadb\eb3fb43bd98e49bd92d5e543ca052dcc\site\wwwroot\node_modules\mongodb\lib\mongodb\db.js:1702:5)
    at g (events.js:185:14)
    at EventEmitter.emit (events.js:115:20)
    at Server.Base._callHandler (\\10.207.188.48\volume-22-default\b6e1596fdce18f78aadb\eb3fb43bd98e49bd92d5e543ca052dcc\site\wwwroot\node_modules\mongodb\lib\mongodb\connection\base.js:130:25)
    at Server.connect.connectionPool.on.server._serverState (\\10.207.188.48\volume-22-default\b6e1596fdce18f78aadb\eb3fb43bd98e49bd92d5e543ca052dcc\site\wwwroot\node_modules\mongodb\lib\mongodb\connection\server.js:517:20)
    at MongoReply.parseBody (\\10.207.188.48\volume-22-default\b6e1596fdce18f78aadb\eb3fb43bd98e49bd92d5e543ca052dcc\site\wwwroot\node_modules\mongodb\lib\mongodb\responses\mongo_reply.js:127:5)
    at Server.connect.connectionPool.on.server._serverState (\\10.207.188.48\volume-22-default\b6e1596fdce18f78aadb\eb3fb43bd98e49bd92d5e543ca052dcc\site\wwwroot\node_modules\mongodb\lib\mongodb\connection\server.js:476:22)
    at EventEmitter.emit (events.js:88:17)
